// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackBtn: typeof import('./src/components/BackBtn.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElRow: typeof import('element-plus/es')['ElRow']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    Header: typeof import('./src/components/HomePage/Header.vue')['default']
    HomeCourse: typeof import('./src/components/HomePage/HomeCourse.vue')['default']
    HomeExplore: typeof import('./src/components/HomePage/HomeExplore.vue')['default']
    HomeGroup: typeof import('./src/components/HomePage/HomeGroup.vue')['default']
    HomeHeader: typeof import('./src/components/HomePage/HomeHeader.vue')['default']
    HomeNews: typeof import('./src/components/HomePage/HomeNews.vue')['default']
    HomePopular: typeof import('./src/components/HomePage/HomePopular.vue')['default']
    NewsContent: typeof import('./src/components/HomePage/NewsContent.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TaiwanMap: typeof import('./src/components/HomePage/TaiwanMap.vue')['default']
    TripCard: typeof import('./src/components/TripCard.vue')['default']
    TripListItem: typeof import('./src/components/TripListItem.vue')['default']
  }
}

export { }
